### ISSUE TITLE
configure mkdocstring for numpydoc

### ISSUE THREAD

**Issue by BalzaniEdoardo** [flatironinstitute/generalized-linear-models#35]
`mkdocstrings` needs to be configured for parsing correctly the numpydoc style. 

This is what I use from the glm package.

```yaml
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy         
            show_source: true
            members_order: source
```

We should add that with a description of the options
